In [7]:
import pandas as pd

In [11]:
x_variable=pd.read_excel(r'./x变量.xlsx')
y_variable=pd.read_excel(r'./y变量.xlsx')

In [13]:
x_variable

     地区    GDP平均值/亿  高中师生比平均值   图书馆藏书平均/万册
0    北京  18091.4000   9.47000  1771.672083
1    天津   8292.9750  11.72500  1289.397708
2    河北  20979.9625  14.64625  1683.252500
3    山西  10221.2875  14.67250  1268.677917
4   内蒙古   9746.7875  15.54500  1017.276875
5    辽宁  16562.2500  14.98250  3013.038958
6    吉林   7813.1250  16.44375  1482.677917
7   黑龙江   9915.2625  14.44750  1671.323958
8    上海  20608.8625   9.85375  6816.598125
9    江苏  50597.2500  12.67875  4910.230208
10   浙江  32327.6500  13.34875  4161.546667
11   安徽  16899.2125  18.11125  1442.488958
12   福建  18840.7750  13.23000  1969.061042
13   江西  11886.0625  16.92500  1608.102500
14   山东  40749.9500  14.08375  3737.538542
15   河南  27267.9875  18.19500  1940.906458
16   湖北  20926.7500  15.83375  2347.755625
17   湖南  19717.7250  15.41125  2111.339375
18   广东  54700.3500  15.58125  5174.730625
19   广西  10569.7750  17.79250  1923.513125
20   海南   2583.4750  16.06000   455.933542
21   重庆  10758.0625  18.22125  1130.632917
22   四川  21862.0250  17.39000  2801.734167
23   贵州   6490.6500  18.38750   998.395625
24   云南  10346.7500  15.45125  1635.827708
25   西藏    686.1750  13.61625    60.270625
26   陕西  12818.1250  16.58875  1181.170208
27   甘肃   4947.9000  16.26375  1073.246250
28   青海   1431.4625  13.99625   372.587708
29   宁夏   1927.6750  16.11000   504.555000
30   新疆   6830.9375  13.48875  1106.369583

In [15]:
y_variable

    总排序   地区  高考报名录取率（2008-2015）      Unnamed: 3
0     1   上海              0.0593        Shanghai
1     2   北京              0.0376         Beijing
2     3   天津              0.0508         Tianjin
3     4   吉林              0.0319           Jilin
4     5   湖北              0.0193           Hubei
5     6   重庆              0.0213       Chongqing
6     7   湖南              0.0150           Hunan
7     8   浙江              0.0205        Zhejiang
8     9   青海              0.0232         Qinghai
9    10  黑龙江              0.0187    Heilongjiang
10   11   辽宁              0.0175        Liaoning
11   12   福建              0.0178          Fujian
12   13   陕西              0.0133         Shaanxi
13   14   广东              0.0140       Guangdong
14   15   宁夏              0.0185         Ningxia
15   16   甘肃              0.0122           Gansu
16   17   四川              0.0133         Sichuan
17   18   江苏              0.0137         Jiangsu
18   19   山东              0.0122        Shandong
19   20   海南              0.0171          Hainan
20   21   新疆              0.0142        Xinjiang
21   22  内蒙古              0.0112  Inner Mongolia
22   23   江西              0.0125         Jiangxi
23   24   河北              0.0110           Hebei
24   25   山西              0.0100          Shanxi
25   26   西藏              0.0117           Tibet
26   27   安徽              0.0088           Anhui
27   28   广西              0.0105         Guangxi
28   29   贵州              0.0104         Guizhou
29   30   云南              0.0105          Yunnan
30   31   河南              0.0083           Henan

In [17]:
merged_df = pd.merge(x_variable,y_variable, on='地区')

In [19]:
merged_df
#merged_df.to_excel(r'/Users/liusheng/Desktop/7004/merged.xlsx')

,地区,GDP平均值/亿,高中师生比平均值,图书馆藏书平均/万册,总排序,高考报名录取率（2008-2015）,Unnamed: 3
0,北京,18091.4000,9.47000,1771.672083,2,0.0376,Beijing
1,天津,8292.9750,11.72500,1289.397708,3,0.0508,Tianjin
2,河北,20979.9625,14.64625,1683.252500,24,0.0110,Hebei
3,山西,10221.2875,14.67250,1268.677917,25,0.0100,Shanxi
4,内蒙古,9746.7875,15.54500,1017.276875,22,0.0112,Inner Mongolia
5,辽宁,16562.2500,14.98250,3013.038958,11,0.0175,Liaoning
6,吉林,7813.1250,16.44375,1482.677917,4,0.0319,Jilin
7,黑龙江,9915.2625,14.44750,1671.323958,10,0.0187,Heilongjiang
8,上海,20608.8625,9.85375,6816.598125,1,0.0593,Shanghai
9,江苏,50597.2500,12.67875,4910.230208,18,0.0137,Jiangsu
10,浙江,32327.6500,13.34875,4161.546667,8,0.0205,Zhejiang
11,安徽,16899.2125,18.11125,1442.488958,27,0.0088,Anhui
12,福建,18840.7750,13.23000,1969.061042,12,0.0178,Fujian
13,江西,11886.0625,16.92500,1608.102500,23,0.0125,Jiangxi
14,山东,40749.9500,14.08375,3737.538542,19,0.0122,Shandong
15,河南,27267.9875,18.19500,1940.906458,31,0.0083,Henan
16,湖北,20926.7500,15.83375,2347.755625,5,0.0193,Hubei
17,湖南,19717.7250,15.41125,2111.339375,7,0.0150,Hunan
18,广东,54700.3500,15.58125,5174.730625,14,0.0140,Guangdong
19,广西,10569.7750,17.79250,1923.513125,28,0.0105,Guangxi
20,海南,2583.4750,16.06000,455.933542,20,0.0171,Hainan
21,重庆,10758.0625,18.22125,1130.632917,6,0.0213,Chongqing
22,四川,21862.0250,17.39000,2801.734167,17,0.0133,Sichuan
23,贵州,6490.6500,18.38750,998.395625,29,0.0104,Guizhou
24,云南,10346.7500,15.45125,1635.827708,30,0.0105,Yunnan
25,西藏,686.1750,13.61625,60.270625,26,0.0117,Tibet
26,陕西,12818.1250,16.58875,1181.170208,13,0.0133,Shaanxi
27,甘肃,4947.9000,16.26375,1073.246250,16,0.0122,Gansu
28,青海,1431.4625,13.99625,372.587708,9,0.0232,Qinghai
29,宁夏,1927.6750,16.11000,504.555000,15,0.0185,Ningxia
30,新疆,6830.9375,13.48875,1106.369583,21,0.0142,Xinjiang

In [21]:
merged_df.rename(columns={'Unnamed: 3': 'region', 'GDP平均值/亿': 'GDP','高中师生比平均值':'student-teacher ratio','高考报名录取率（2008-2015）':'University Acceptance Rate','图书馆藏书平均/万册':'library collection'}, inplace=True)

In [23]:
merged_df

,地区,GDP,student-teacher ratio,library collection,总排序,University Acceptance Rate,region
0,北京,18091.4000,9.47000,1771.672083,2,0.0376,Beijing
1,天津,8292.9750,11.72500,1289.397708,3,0.0508,Tianjin
2,河北,20979.9625,14.64625,1683.252500,24,0.0110,Hebei
3,山西,10221.2875,14.67250,1268.677917,25,0.0100,Shanxi
4,内蒙古,9746.7875,15.54500,1017.276875,22,0.0112,Inner Mongolia
5,辽宁,16562.2500,14.98250,3013.038958,11,0.0175,Liaoning
6,吉林,7813.1250,16.44375,1482.677917,4,0.0319,Jilin
7,黑龙江,9915.2625,14.44750,1671.323958,10,0.0187,Heilongjiang
8,上海,20608.8625,9.85375,6816.598125,1,0.0593,Shanghai
9,江苏,50597.2500,12.67875,4910.230208,18,0.0137,Jiangsu
10,浙江,32327.6500,13.34875,4161.546667,8,0.0205,Zhejiang
11,安徽,16899.2125,18.11125,1442.488958,27,0.0088,Anhui
12,福建,18840.7750,13.23000,1969.061042,12,0.0178,Fujian
13,江西,11886.0625,16.92500,1608.102500,23,0.0125,Jiangxi
14,山东,40749.9500,14.08375,3737.538542,19,0.0122,Shandong
15,河南,27267.9875,18.19500,1940.906458,31,0.0083,Henan
16,湖北,20926.7500,15.83375,2347.755625,5,0.0193,Hubei
17,湖南,19717.7250,15.41125,2111.339375,7,0.0150,Hunan
18,广东,54700.3500,15.58125,5174.730625,14,0.0140,Guangdong
19,广西,10569.7750,17.79250,1923.513125,28,0.0105,Guangxi
20,海南,2583.4750,16.06000,455.933542,20,0.0171,Hainan
21,重庆,10758.0625,18.22125,1130.632917,6,0.0213,Chongqing
22,四川,21862.0250,17.39000,2801.734167,17,0.0133,Sichuan
23,贵州,6490.6500,18.38750,998.395625,29,0.0104,Guizhou
24,云南,10346.7500,15.45125,1635.827708,30,0.0105,Yunnan
25,西藏,686.1750,13.61625,60.270625,26,0.0117,Tibet
26,陕西,12818.1250,16.58875,1181.170208,13,0.0133,Shaanxi
27,甘肃,4947.9000,16.26375,1073.246250,16,0.0122,Gansu
28,青海,1431.4625,13.99625,372.587708,9,0.0232,Qinghai
29,宁夏,1927.6750,16.11000,504.555000,15,0.0185,Ningxia
30,新疆,6830.9375,13.48875,1106.369583,21,0.0142,Xinjiang

In [25]:
df_new=merged_df[['region','University Acceptance Rate','GDP','student-teacher ratio','library collection']].copy()

In [27]:
df_new

,region,University Acceptance Rate,GDP,student-teacher ratio,library collection
0,Beijing,0.0376,18091.4000,9.47000,1771.672083
1,Tianjin,0.0508,8292.9750,11.72500,1289.397708
2,Hebei,0.0110,20979.9625,14.64625,1683.252500
3,Shanxi,0.0100,10221.2875,14.67250,1268.677917
4,Inner Mongolia,0.0112,9746.7875,15.54500,1017.276875
5,Liaoning,0.0175,16562.2500,14.98250,3013.038958
6,Jilin,0.0319,7813.1250,16.44375,1482.677917
7,Heilongjiang,0.0187,9915.2625,14.44750,1671.323958
8,Shanghai,0.0593,20608.8625,9.85375,6816.598125
9,Jiangsu,0.0137,50597.2500,12.67875,4910.230208
10,Zhejiang,0.0205,32327.6500,13.34875,4161.546667
11,Anhui,0.0088,16899.2125,18.11125,1442.488958
12,Fujian,0.0178,18840.7750,13.23000,1969.061042
13,Jiangxi,0.0125,11886.0625,16.92500,1608.102500
14,Shandong,0.0122,40749.9500,14.08375,3737.538542
15,Henan,0.0083,27267.9875,18.19500,1940.906458
16,Hubei,0.0193,20926.7500,15.83375,2347.755625
17,Hunan,0.0150,19717.7250,15.41125,2111.339375
18,Guangdong,0.0140,54700.3500,15.58125,5174.730625
19,Guangxi,0.0105,10569.7750,17.79250,1923.513125
20,Hainan,0.0171,2583.4750,16.06000,455.933542
21,Chongqing,0.0213,10758.0625,18.22125,1130.632917
22,Sichuan,0.0133,21862.0250,17.39000,2801.734167
23,Guizhou,0.0104,6490.6500,18.38750,998.395625
24,Yunnan,0.0105,10346.7500,15.45125,1635.827708
25,Tibet,0.0117,686.1750,13.61625,60.270625
26,Shaanxi,0.0133,12818.1250,16.58875,1181.170208
27,Gansu,0.0122,4947.9000,16.26375,1073.246250
28,Qinghai,0.0232,1431.4625,13.99625,372.587708
29,Ningxia,0.0185,1927.6750,16.11000,504.555000
30,Xinjiang,0.0142,6830.9375,13.48875,1106.369583

In [29]:
import numpy as np
df=df_new.copy()

In [49]:
import statsmodels.api as sm


# 假设我们对'feature1', 'feature2', 'feature3'这三列取对数
df['GDP'] = np.log1p(df['GDP'])
#df_new['student-teacher ratio'] = np.log1p(df_new['student-teacher ratio'])
df['library collection'] = np.log1p(df['library collection'])
#df_new['University Acceptance Rate']== np.log1p(df_new['University Acceptance Rate'])



X = df[['GDP', 'student-teacher ratio', 'library collection']]# 特征列
X1= df[['GDP', 'student-teacher ratio']]
X2= df[['GDP']]


#X = df_new[['GDP', 'student-teacher ratio']]  # 特征列
y = df['University Acceptance Rate']  # 目标变量列

# 为特征数据添加一列常数项，以便进行线性回归
X = sm.add_constant(X)

# 创建线性回归模型
model = sm.OLS(y, X).fit()
model1 = sm.OLS(y, sm.add_constant(X1)).fit()
model2 = sm.OLS(y, sm.add_constant(X2)).fit()

# 打印模型的摘要，其中包括参数估计、t值、p值等统计信息
#print(model.summary())

In [33]:
df_new.describe()

,University Acceptance Rate,GDP,student-teacher ratio,library collection
count,31.000000,31.000000,31.000000,31.000000
mean,0.018268,16367.697984,15.114556,2021.350081
std,0.011764,13294.155701,2.268879,1521.917081
min,0.008300,686.175000,9.470000,60.270625
25%,0.011450,8053.050000,13.806250,1118.501250
50%,0.014000,11886.062500,15.451250,1635.827708
75%,0.019000,20767.806250,16.516250,2229.547500
max,0.059300,54700.350000,18.387500,6816.598125

In [67]:
from tabulate import tabulate
desc_stats = df_new.describe().transpose()
table = tabulate(desc_stats, headers='keys', tablefmt='latex', showindex='never', floatfmt=".2f")
print(table)

\begin{tabular}{rrrrrrrr}
\hline
   count &     mean &      std &    min &     25\% &      50\% &      75\% &      max \\
\hline
   31.00 &     0.02 &     0.01 &   0.01 &    0.01 &     0.01 &     0.02 &     0.06 \\
   31.00 & 16367.70 & 13294.16 & 686.17 & 8053.05 & 11886.06 & 20767.81 & 54700.35 \\
   31.00 &    15.11 &     2.27 &   9.47 &   13.81 &    15.45 &    16.52 &    18.39 \\
   31.00 &  2021.35 &  1521.92 &  60.27 & 1118.50 &  1635.83 &  2229.55 &  6816.60 \\
\hline
\end{tabular}

In [59]:
summary_col([model, model1, model2], model_names=['Model', 'Model1', 'Model2'], stars=True,info_dict = {'':lambda x: '',
                                                 '':lambda x: '',
                                                 'Observation':lambda x:str(int(x.nobs)),
                                                 })

<class 'statsmodels.iolib.summary2.Summary'>
"""

====================================================
                        Model      Model1    Model2
----------------------------------------------------
const                 0.1121***  0.0777*    0.0157
                      (0.0380)   (0.0404)   (0.0497)
GDP                   -0.1058**  -0.0034    0.0011
                      (0.0385)   (0.0164)   (0.0213)
student-teacher ratio -0.0032*** -0.0034***
                      (0.0007)   (0.0007)
library collection    0.0950***
                      (0.0331)
R-squared             0.5651     0.4324     0.0001
R-squared Adj.        0.5168     0.3918     -0.0344

Observation           31         31         31
====================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01
"""